<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Princes-MBP.hitronhub.home" ignored="0" name="TestNGTest" tests="11" failures="2" timestamp="2023-02-27T19:36:47 CST" time="0.068" errors="0">
  <testcase name="test1" time="0.008" classname="Tutorial.Session9"/>
  <testcase name="test2" time="0.002" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="Tutorial.Session9">
    <failure type="java.lang.AssertionError" message="expected [12] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [10]
at Tutorial.Session9.test2(Session9.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.001" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.001" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.001" classname="Tutorial.Session9">
    <failure type="java.lang.AssertionError" message="expected [11] but found [15]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [15]
at Tutorial.Session9.test4(Session9.java:28)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test3" time="0.0" classname="Tutorial.Session9">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="package2test" time="0.0" classname="practice.NewTest2"/>
</testsuite> <!-- TestNGTest -->
